import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainSection from '../components/organisms/main_section'
import Header from '../components/organisms/header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainSection />
    </div>
  )
}
