import Head from 'next/head'
import { Provider } from 'react-redux'
import styles from '../styles/Home.module.css'
import MainSection from '../src/components/organisms/main_section'
import Header from '../src/components/organisms/header'
import store from '../src/redux/store'

export default function Home() {
  return (
    <Provider store={store}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <MainSection />
      </div>
    </Provider>
  )
}
